package raft

import (
	"bytes"
	"errors"
	"testing"
)

func samplePreVote() PreVoteRequest {
	return PreVoteRequest{ProspectiveTerm: 8, CandidateID: 3, LastLogIndex: 42, LastLogTerm: 7}
}

func TestPreVoteEncodeDecodeRoundTrip(t *testing.T) {
	req := samplePreVote()
	got, err := DecodePreVote(EncodePreVote(req))
	if err != nil {
		t.Fatalf("DecodePreVote: %v", err)
	}
	if got != req {
		t.Fatalf("got %+v, want %+v", got, req)
	}
}

// TestPreVoteKnownByteVector independently derives the expected wire
// bytes for prospectiveTerm=8, candidateID=3, lastLogIndex=42,
// lastLogTerm=7 — not generated by round-tripping through the production
// encoder.
func TestPreVoteKnownByteVector(t *testing.T) {
	got := EncodePreVote(samplePreVote())
	want := []byte{
		0, 0, 0, 0, 0, 0, 0, 8, // prospectiveTerm
		0, 0, 0, 0, 0, 0, 0, 3, // candidateID
		0, 0, 0, 0, 0, 0, 0, 42, // lastLogIndex
		0, 0, 0, 0, 0, 0, 0, 7, // lastLogTerm
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("bytes:\n got  % x\n want % x", got, want)
	}
}

func TestDecodePreVoteTooShort(t *testing.T) {
	_, err := DecodePreVote([]byte{1, 2, 3})
	if !errors.Is(err, ErrMalformedRPC) {
		t.Fatalf("err = %v, want ErrMalformedRPC", err)
	}
}

func TestDecodePreVoteTrailingBytes(t *testing.T) {
	buf := append(EncodePreVote(samplePreVote()), 0xFF)
	_, err := DecodePreVote(buf)
	if !errors.Is(err, ErrMalformedRPC) {
		t.Fatalf("err = %v, want ErrMalformedRPC", err)
	}
}

// TestPreVoteZeroCandidateIDRoundTrips proves a zero CandidateID is not
// itself rejected at the wire-codec layer — NodeID validity (zero is
// reserved/invalid) is a Configuration-level rule enforced elsewhere
// (see membership.go's NewConfiguration), not a wire-encoding concern;
// the codec must not silently corrupt or reject a value it isn't its job
// to validate.
func TestPreVoteZeroCandidateIDRoundTrips(t *testing.T) {
	req := PreVoteRequest{ProspectiveTerm: 1, CandidateID: 0, LastLogIndex: 0, LastLogTerm: 0}
	got, err := DecodePreVote(EncodePreVote(req))
	if err != nil {
		t.Fatalf("DecodePreVote: %v", err)
	}
	if got != req {
		t.Fatalf("got %+v, want %+v", got, req)
	}
}

func TestPreVoteResponseEncodeDecodeRoundTrip(t *testing.T) {
	for _, granted := range []bool{true, false} {
		resp := PreVoteResponse{Term: 9, VoteGranted: granted}
		got, err := DecodePreVoteResponse(EncodePreVoteResponse(resp))
		if err != nil {
			t.Fatalf("DecodePreVoteResponse: %v", err)
		}
		if got != resp {
			t.Fatalf("got %+v, want %+v", got, resp)
		}
	}
}

// TestPreVoteResponseKnownByteVector independently derives the expected
// wire bytes for term=9, voteGranted=true.
func TestPreVoteResponseKnownByteVector(t *testing.T) {
	got := EncodePreVoteResponse(PreVoteResponse{Term: 9, VoteGranted: true})
	want := []byte{
		0, 0, 0, 0, 0, 0, 0, 9, // term
		1, // voteGranted = true
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("bytes:\n got  % x\n want % x", got, want)
	}
}

func TestDecodePreVoteResponseTooShort(t *testing.T) {
	_, err := DecodePreVoteResponse([]byte{1, 2, 3})
	if !errors.Is(err, ErrMalformedRPC) {
		t.Fatalf("err = %v, want ErrMalformedRPC", err)
	}
}

func TestDecodePreVoteResponseInvalidGrantedByte(t *testing.T) {
	buf := EncodePreVoteResponse(PreVoteResponse{Term: 1, VoteGranted: true})
	buf[8] = 7
	_, err := DecodePreVoteResponse(buf)
	if !errors.Is(err, ErrMalformedRPC) {
		t.Fatalf("err = %v, want ErrMalformedRPC", err)
	}
}

func TestDecodePreVoteResponseTrailingBytes(t *testing.T) {
	buf := append(EncodePreVoteResponse(PreVoteResponse{Term: 1, VoteGranted: true}), 0xFF)
	_, err := DecodePreVoteResponse(buf)
	if !errors.Is(err, ErrMalformedRPC) {
		t.Fatalf("err = %v, want ErrMalformedRPC", err)
	}
}
